/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accueil: (typeof import("./src/components/étapes/Accueil.vue"))["default"]
    'AjoutDonnée': typeof import('./src/components/étapes/démo/AjoutDonnée.vue')['default']
    'CarteFonctionalité': typeof import('./src/components/CarteFonctionalité.vue')['default']
    'CarteTéléchargement': typeof import('./src/components/CarteTéléchargement.vue')['default']
    CarteUtilisation: typeof import('./src/components/CarteUtilisation.vue')['default']
    copy: (typeof import("./src/components/étapes/SectionAccueil copy.vue"))["default"]
    'ÉtapeCours': typeof import('./src/components/ÉtapeCours.vue')['default']
    IndiceInstallationApple: typeof import('./src/components/IndiceInstallationApple.vue')['default']
    InfoStation: typeof import('./src/components/étapes/démo/InfoStation.vue')['default']
    'ItemLangueProgrès': typeof import('./src/components/ItemLangueProgrès.vue')['default']
    MarqueurSite: (typeof import("./src/components/étapes/démo/MarqueurSite.vue"))["default"]
    MarqueurStation: typeof import('./src/components/étapes/démo/MarqueurStation.vue')['default']
    MenuLangues: typeof import('./src/components/MenuLangues.vue')['default']
    'MesDonnées': typeof import('./src/components/étapes/démo/MesDonnées.vue')['default']
    PageAccueil: (typeof import("./src/components/étapes/PageAccueil.vue"))["default"]
    PagePrincipale: typeof import('./src/components/PagePrincipale.vue')['default']
    'PageTéléchargements': (typeof import("./src/components/PageTéléchargements.vue"))["default"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionAccueil: typeof import('./src/components/étapes/SectionAccueil.vue')['default']
    SectionCode: typeof import('./src/components/étapes/SectionCode.vue')['default']
    'SectionDémo': typeof import('./src/components/étapes/démo/SectionDémo.vue')['default']
    SectionObtConstellation: typeof import('./src/components/étapes/SectionObtConstellation.vue')['default']
    'SectionTéléchargerDonnées': typeof import('./src/components/étapes/SectionTéléchargerDonnées.vue')['default']
    TitreSection: typeof import('./src/components/TitreSection.vue')['default']
  }
}
