/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'AjoutDonnée': typeof import('./src/components/étapes/démo/AjoutDonnée.vue')['default']
    BtnMenuLangues: typeof import('./src/components/BtnMenuLangues.vue')['default']
    CarteConnexions: typeof import('./src/components/étapes/démo/CarteConnexions.vue')['default']
    CarteLien: typeof import('./src/components/étapes/communs/CarteLien.vue')['default']
    'EntréeDonnée': typeof import('./src/components/étapes/démo/EntréeDonnée.vue')['default']
    'ÉtapeCours': typeof import('./src/components/ÉtapeCours.vue')['default']
    GraphiqueStation: typeof import('./src/components/étapes/démo/GraphiqueStation.vue')['default']
    'ItemLangueProgrès': typeof import('./src/components/ItemLangueProgrès.vue')['default']
    MarqueurStation: typeof import('./src/components/étapes/démo/MarqueurStation.vue')['default']
    MenuLangues: typeof import('./src/components/MenuLangues.vue')['default']
    'MesDonnées': typeof import('./src/components/étapes/démo/MesDonnées.vue')['default']
    PagePrincipale: typeof import('./src/components/PagePrincipale.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionAccueil: typeof import('./src/components/étapes/SectionAccueil.vue')['default']
    SectionCode: typeof import('./src/components/étapes/SectionCode.vue')['default']
    'SectionDémo': typeof import('./src/components/étapes/démo/SectionDémo.vue')['default']
    SectionObtConstellation: typeof import('./src/components/étapes/obtConstellation/SectionObtConstellation.vue')['default']
    'SectionTéléchargerDonnées': typeof import('./src/components/étapes/SectionTéléchargerDonnées.vue')['default']
    TitreSection: typeof import('./src/components/TitreSection.vue')['default']
  }
}
